backend:
  name: git-gateway
  branch: master 
media_folder: "uploads" 
collections:
  - name: "news" 
    label: "News" 
    folder: "_posts" 
    create: true 
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" 
    fields: 
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Categories", name: "categories", widget: "string", required: false}
      - {label: "Author", name: "author", widget: "string", required: false}
      - {label: "CoAuthor", name: "coauthor", widget: "string"}
			- {label: "Description", name: "description", widget: "string"}
